# Generated by Django 5.1.1 on 2024-10-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name='Day task was sent')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed or Not')),
                ('cancelled', models.BooleanField(default=False, verbose_name='cancelled or not')),
            ],
        ),
    ]
