# Generated by Django 5.1.1 on 2024-10-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_additional_notes_order_page_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sent_date',
            field=models.DateField(auto_now_add=True, verbose_name='Day task was sent'),
        ),
    ]
